# Generated by Django 5.0.4 on 2024-05-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_video_remove_user_uploaded_at_remove_user_video_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
    ]
